title: 您的产品名称 | 简洁清晰的产品主页
description: 这是一个使用 GitHub Pages 和 Jekyll 快速搭建的免费产品主页或博客。
baseurl: "" # 如果是 <用户名>.github.io，留空。如果是项目子页，填上 /项目名
url: "https://bigbeijibear.github.io"

# Jekyll Build Settings
themes: jekyll-theme-minimal
plugins:
  - jekyll-feed

# 导航栏链接
header_links:
  Home: /
  Blog: /blog
  
